#!/bin/bash -l  
# Use the current working directory
#SBATCH -D ./
# Use the current environment for this job.
##SBATCH --export=ALL
# Define job name
#SBATCH -J TM_solver
# Define a standard output file. When the job is running, %u will be replaced by user name,
# %N will be replaced by the name of the node that runs the batch script, and %j will be replaced by job id number.
#SBATCH -o ./SLURM_OUT/TM_solver.%u.%N.%j.out
# Define a standard error file
#SBATCH -e ./SLURM_OUT/TM_solver.%u.%N.%j.err
# Request the partition
#SBATCH -p nodes 
# Request the number of nodes
#SBATCH -N 1 
# Request the total number of cores
#SBATCH -n 48 
# This asks for 0 days, 23 hours, 59 minutes and 59 seconds of time.
#SBATCH -t 23:59:59
# Specify memory
#SBATCH --mem=500000M

module load julia/1.11.6

julia --project=./TMenv solve_cyclo_thetao.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp1"  
julia --project=./TMenv solve_cyclo_so.jl      "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp1"  
julia --project=./TMenv solve_cyclo_agessc.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp1"  

julia --project=./TMenv solve_cyclo_thetao.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp2"  
julia --project=./TMenv solve_cyclo_so.jl      "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp2"  
julia --project=./TMenv solve_cyclo_agessc.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp2"  

julia --project=./TMenv solve_cyclo_thetao.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp3"  
julia --project=./TMenv solve_cyclo_so.jl      "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp3"  
julia --project=./TMenv solve_cyclo_agessc.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp3"  

julia --project=./TMenv solve_cyclo_thetao.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp4"  
julia --project=./TMenv solve_cyclo_so.jl      "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp4"  
julia --project=./TMenv solve_cyclo_agessc.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp4"  

julia --project=./TMenv solve_cyclo_thetao.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp5"  
julia --project=./TMenv solve_cyclo_so.jl      "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp5"  
julia --project=./TMenv solve_cyclo_agessc.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp5"  

julia --project=./TMenv solve_cyclo_thetao.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp6"  
julia --project=./TMenv solve_cyclo_so.jl      "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp6"  
julia --project=./TMenv solve_cyclo_agessc.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp6"  

julia --project=./TMenv solve_cyclo_thetao.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp7"  
julia --project=./TMenv solve_cyclo_so.jl      "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp7"  
julia --project=./TMenv solve_cyclo_agessc.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp7"  

julia --project=./TMenv solve_cyclo_thetao.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp8"  
julia --project=./TMenv solve_cyclo_so.jl      "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp8"  
julia --project=./TMenv solve_cyclo_agessc.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp8"  

julia --project=./TMenv solve_cyclo_thetao.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp9"  
julia --project=./TMenv solve_cyclo_so.jl      "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp9"  
julia --project=./TMenv solve_cyclo_agessc.jl  "../data/processed/cyclo_stationary/IPSL-CM6A-LR_r1i2p1f1_monthly" "_exp9"  
